print('猫1の名前を入力してください。')
cat_name1 = input()
print('猫2の名前を入力してください。')
cat_name2 = input()
print('猫3の名前を入力してください。')
cat_name3 = input()
print('猫4の名前を入力してください。')
cat_name4 = input()
print('猫5の名前を入力してください。')
cat_name5 = input()
print('猫6の名前を入力してください。')
cat_name6 = input()
print('猫の名前は次のとおり:')
print(cat_name1 + ' ' + cat_name2 + ' ' + cat_name3 + ' ' + cat_name4 + ' ' + cat_name5 + ' ' + cat_name6)
